# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 141fb36f593b06fe485db72623d18094c09b968734bc50a0bd6232edaa25d73211bb940e660e316fb34a3732f523e0d286c5fcbc46d74af45e4663345b0d13b0

test:
  secret_key_base: 9f06cab79b3253776c45ff5de7547cde035b54364702009c348b482a0a9284d1d8edd9941b12e9fbe4d8e8dc881bbd27122ce375e305c42a76c8bf84ee68f538

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
